name: Add GTFS Archive to Release
on:
  release:
    types:
      - created

jobs:
  add_test_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download current GTFS Archive
        run: |
          wget $(curl 'https://registry.npmjs.org/sample-gtfs-feed/latest' -H 'Accept: application/json' -fsSL | jq -rc .dist.tarball)
          mv sample-gtfs-feed-*.tgz gtfs-sample-feed.tgz

      - name: Upload GTFS Archive
        uses: actions/upload-artifact@v2
        with:
          name: gtfs-sample-feed
          path: gtfs-sample-feed.tgz

      - name: Attach GTFS Archive to Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: gtfs-sample-feed.tgz
          args: |
            --name "${{ github.event.release.tag_name }}"
            --body "GTFS Archive for release ${{ github.event.release.tag_name }}"
            --target "${{ github.event.release.target_commitish }}"
